{{- if .Values.secret.enabled -}}
{{- $fullName := include "App2.fullname" . -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "App2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "App2.name" . }}
    helm.sh/chart: {{ include "App2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }} 
{{- end }}
